version: 2

jobs:
  build:
    docker:
      - image: wordpress
        environment:
          WORDPRESS_DB_USER: exampleuser
          WORDPRESS_DB_PASSWORD: examplepass
          WORDPRESS_DB_NAME: exampledb

      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: exampledb
          MYSQL_USER: exampleuser
          MYSQL_PASSWORD: examplepass
          MYSQL_RANDOM_ROOT_PASSWORD: '1'

    steps:
      - checkout
      # - run:
      #     name: install mysql-client
      #     command: sudo apt install -y mysql-client

      - run:
          name: install wp-cli
          command: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            mv wp-cli.phar /usr/local/bin/wp
            wp --info
          
      - run:
          name: wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: download, config, and install WordPress
          command: |
            # wp core download
            # wp config create --dbhost=127.0.0.1 --dbname=$WORDPRESS_DB_NAME --dbuser=$WORDPRESS_DB_USER --dbpass=$WORDPRESS_DB_PASSWORD
            wp core install --url=localhost --title=test --admin_user=test --admin_password=test --admin_email=test@example.com