version: 2

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Set up network
          command: |
            docker network create wp-network
      - run:
          name: Set up database
          command: |
            docker run -d \
              -e MYSQL_ROOT_PASSWORD=1234 \
              -e MYSQL_DATABASE=wordpress \
              -e MYSQL_USER=wordpress \
              -e MYSQL_PASSWORD=wordpress \
              --name db \
              --network wp-network \
              mysql
      - run:
          name: Run WordPress
          command: |
            docker run -d \
              -e WORDPRESS_DB_HOST=db:3306 \
              -e WORDPRESS_DB_USER=root \
              -e WORDPRESS_DB_PASSWORD=1234 \
              -e WORDPRESS_DB_NAME=wordpress \
              --name wp-container \
              --network wp-network \
              wordpress
      - run:
          name: Run WordPress CLI
          command: |
            docker run -it --rm \
              --volumes-from wp-container \
              --network wp-network \
              wordpress:cli core install
#       - run:
#           name: Install plugin
#           command: |
#             docker exec -it wp-container wp plugin install ghost-inspector
